spring.application.name=personal-management

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

app.jwt.private-key=${JWT_PRIVATE_KEY}
app.jwt.public-key=${JWT_PUBLIC_KEY}
app.jwt-expiration-milliseconds=${JWT_EXPIRATION} 